DECLARE
    v_count  INT;
    v_name VARCHAR2(20);
    TYPE namesarray IS VARRAY(11) OF VARCHAR2(20);
    names    namesarray;
BEGIN
    names := namesarray('countries', 'addresses', 'team_status', 'teams', 'drivers', 'seasons',
                       'circuits', 'races', 'races_results_status', 'races_results',
                       'races_qualifying');

    FOR i IN 1..names.count LOOP
        v_name := names(i);

        SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = upper(v_name);
        IF v_count = 1 THEN
            DBMS_OUTPUT.PUT_LINE('Dropping table: ' || v_name);
            EXECUTE IMMEDIATE 'DROP TABLE '|| v_name || ' CASCADE CONSTRAINTS';
        END IF;
    END LOOP;
END;

/

CREATE TABLE countries
(
  country_id NUMBER (4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100  CONSTRAINT countries_pk PRIMARY KEY,
  name VARCHAR2 (40) NOT NULL
 );

CREATE TABLE addresses
(
  address_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100  CONSTRAINT addr_pk PRIMARY KEY,
  street VARCHAR2 (40) NOT NULL ,
  postal_code VARCHAR2 (40 ) ,
  city VARCHAR2 (40 ) NOT NULL ,
  country_id NUMBER (4) NOT NULL CONSTRAINT addr_country_fk REFERENCES countries (country_id)
 );

 CREATE TABLE team_status
 (
    status_id NUMBER CONSTRAINT team_status_pk PRIMARY KEY,
    name VARCHAR2 (40) NOT NULL
 );

 CREATE TABLE teams
 (
    team_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT teams_pk PRIMARY KEY,
    name VARCHAR2 (40) NOT NULL,
    engine_suplier VARCHAR2 (40),
    principal VARCHAR2 (40),
    established DATE ,
    team_status_id CONSTRAINT team_team_status_fk REFERENCES team_status (status_id) ,
    address_id NUMBER (4) NOT NULL CONSTRAINT team_addr_fk REFERENCES addresses (address_id)
 );

 CREATE TABLE drivers
 (
    driver_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT drivers_pk PRIMARY KEY,
    name VARCHAR2 (40) NOT NULL,
    surname VARCHAR2 (40) NOT NULL,
    birth_date DATE NOT NULL,
    gender CHAR (1) CONSTRAINT emp_gender_check CHECK (gender IN ('M', 'F', 'N')),
    nationality NUMBER (4) NOT NULL CONSTRAINT driver_country_fk REFERENCES countries (country_id),
    race_number NUMBER (2) NOT NULL
 );

 CREATE TABLE seasons
 (
    season_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 50 CONSTRAINT seasons_pk PRIMARY KEY,
    year NUMBER (4),
    description VARCHAR2 (40)
 );

 CREATE TABLE circuits
 (
    circuit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT circuits_pk PRIMARY KEY,
    name VARCHAR2 (40) NOT NULL,
    address_id NOT NULL CONSTRAINT circuit_address_fk REFERENCES addresses (address_id),
    length NUMBER (5, 3) NOT NULL,
    turn_count NUMBER (2) NOT NULL
 );

 CREATE TABLE races
 (
    race_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT races_pk PRIMARY KEY,
    season_id NUMBER NOT NULL CONSTRAINT race_season_fk REFERENCES seasons (season_id),
    name VARCHAR2 (40) NOT NULL,
    date_hosted DATE,
    circuit_id NUMBER NOT NULL CONSTRAINT race_circuit_fk REFERENCES circuits (circuit_id)
 );

 CREATE TABLE races_results_status
 (
    status_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT rc_res_status_pk PRIMARY KEY,
    name VARCHAR (40) NOT NULL
 );

 CREATE TABLE races_results
 (
    result_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT rc_result_pk PRIMARY KEY,
    race_id NUMBER NOT NULL CONSTRAINT result_race_fk REFERENCES races (race_id),
    driver_id NUMBER NOT NULL CONSTRAINT result_driver_fk REFERENCES drivers (driver_id),
    team_id NUMBER NOT NULL CONSTRAINT result_team_fk REFERENCES teams (team_id),
    finishing_position NUMBER (2) NOT NULL,
    points NUMBER (4, 1) NOT NULL,
    status_id NUMBER NOT NULL CONSTRAINT result_status_fk REFERENCES races_results_status (status_id),
    CONSTRAINT unique_race_driver UNIQUE (race_id, driver_id)
 );

 CREATE TABLE races_qualifying
 (
    qualifying_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT rc_qualifying_pk PRIMARY KEY,
    race_id NUMBER NOT NULL CONSTRAINT qualifying_race_fk REFERENCES races (race_id),
    driver_id NUMBER NOT NULL CONSTRAINT qualifying_driver_fk REFERENCES drivers (driver_id),
    team_id NUMBER NOT NULL CONSTRAINT qualifying_team_fk REFERENCES teams (team_id),
    q1_time INTERVAL DAY(0) TO SECOND(3),
    q2_time INTERVAL DAY(0) TO SECOND(3),
    q3_time INTERVAL DAY(0) TO SECOND(3),
    starting_pos NUMBER (2),
    CONSTRAINT unique_qual_driver UNIQUE (race_id, driver_id)
 );